<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold text-gray-800">{{ $title }}</h2></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
        <div class="border-b border-slate-200 bg-slate-50 px-5 py-5"><div class="grid gap-4 md:grid-cols-[1fr_auto_auto] md:items-center"><p class="text-sm text-slate-600">{{ $description }}</p><div class="flex items-center gap-3"><div class="flex items-center rounded-2xl border border-slate-200 bg-white px-3 py-2 shadow-sm"><svg class="h-4 w-4 text-slate-500" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-4.35-4.35M11 19a8 8 0 100-16 8 8 0 000 16z"></path></svg><input id="mapping-search" type="text" placeholder="Search" class="ml-2 w-36 bg-transparent text-sm text-slate-900 placeholder:text-slate-400 outline-none"></div>@if(data_get($permissions, 'export'))<button type="button" onclick="exportMappingTable('csv')" class="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-100">Export CSV</button><button type="button" onclick="exportMappingTable('xlsx')" class="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700 hover:bg-emerald-100">Export XLSX</button><button type="button" onclick="exportMappingTable('pdf')" class="rounded-lg border border-purple-200 bg-purple-50 px-3 py-2 text-sm font-semibold text-purple-700 hover:bg-purple-100">Export PDF</button>@endif</div><div class="flex justify-end">@if(data_get($permissions, 'create'))<button type="button" onclick="openMappingModal()" class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700">Add New</button>@endif</div></div></div>
        @if(session('success') || session('error'))<div class="px-5 py-4"><div class="rounded-2xl px-4 py-3 text-sm font-semibold {{ session('success') ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700' }}">{{ session('success') ?? session('error') }}</div></div>@endif
        <div class="overflow-x-auto"><div class="max-h-[420px] overflow-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="sticky top-0 z-10 bg-purple-100"><tr><th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-[0.2em] text-purple-900">Group</th><th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-[0.2em] text-purple-900">Project</th><th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-[0.2em] text-purple-900">Application</th><th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-[0.2em] text-purple-900">Status</th><th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-[0.2em] text-purple-900">Actions</th></tr></thead><tbody class="divide-y divide-slate-200 bg-white">
            @forelse($mappings as $mapping)<tr><td class="px-5 py-3 text-sm font-semibold text-slate-900">{{ $mapping->group_name }}</td><td class="px-5 py-3 text-sm text-slate-600">{{ $mapping->project_name }}</td><td class="px-5 py-3 text-sm text-slate-600">{{ $mapping->application_name }}</td><td class="px-5 py-3 text-sm"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $mapping->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }}">{{ $mapping->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-5 py-3 text-sm">@if((int) $mapping->is_active === 1 && data_get($permissions, 'deactivate'))<form method="POST" action="{{ route('group.project.application.mapping.toggle', $mapping->mapping_id) }}" class="inline">@csrf<button class="rounded-lg bg-rose-100 px-2.5 py-1.5 text-xs font-semibold text-rose-700 hover:bg-rose-200">Disable</button></form>@elseif((int) $mapping->is_active !== 1 && data_get($permissions, 'activate'))<form method="POST" action="{{ route('group.project.application.mapping.toggle', $mapping->mapping_id) }}" class="inline">@csrf<button class="rounded-lg bg-emerald-100 px-2.5 py-1.5 text-xs font-semibold text-emerald-700 hover:bg-emerald-200">Activate</button></form>@endif</td></tr>@empty<tr class="empty-row"><td colspan="5" class="px-5 py-8 text-center text-sm text-slate-500">No mappings found.</td></tr>@endforelse
        </tbody></table></div></div>
    </div></div></div>
    <div id="mapping-modal" class="fixed inset-0 z-50 hidden bg-slate-900/60 px-4 py-8"><div class="mx-auto max-w-xl rounded-3xl bg-white shadow-2xl"><form method="POST" action="{{ route('group.project.application.mapping.store') }}">@csrf
        <div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h3 class="text-lg font-semibold">Map Group Applications</h3><button type="button" onclick="closeMappingModal()" class="rounded-full bg-slate-100 px-3 py-1">×</button></div><div class="space-y-4 px-5 py-5">
            <div><label class="mb-1 block text-sm font-medium">Select Group</label><select name="group_id" required class="w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="">Select group</option>@foreach($groups as $group)<option value="{{ $group->group_id }}">{{ $group->group_name }}</option>@endforeach</select></div>
            <div><label class="mb-1 block text-sm font-medium">Select Project</label><select id="mapping-project" name="project_id" required class="w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="">Select project</option>@foreach($projects as $project)<option value="{{ $project->project_id }}">{{ $project->project_name }}</option>@endforeach</select></div>
            <div><label class="mb-1 block text-sm font-medium">Select Application</label><div id="application-select" class="relative"><div class="flex min-h-[4rem] flex-wrap items-center gap-2 rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 shadow-sm transition focus-within:border-slate-400 focus-within:ring-1 focus-within:ring-emerald-100" data-multi-select="applications"><div class="flex flex-wrap gap-2" data-multi-select-chips></div><input type="text" class="min-w-[140px] flex-1 bg-transparent text-sm text-slate-900 placeholder:text-slate-400 outline-none" placeholder="Search and select applications" data-multi-select-input autocomplete="off"></div><div class="absolute left-0 right-0 z-50 mt-1 hidden max-h-60 overflow-auto rounded-xl border border-slate-200 bg-white shadow-xl" data-multi-select-list></div><div data-multi-select-hidden class="hidden"></div></div></div>
            <div class="flex justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" onclick="closeMappingModal()" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold">Cancel</button><button class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Save</button></div>
        </div></form></div></div>
    <script>
        const applicationOptionsUrl = '{{ url('/group-project-application-mapping/applications') }}';
        const applicationSelect = document.querySelector('[data-multi-select="applications"]');
        const applicationContainer = document.getElementById('application-select');
        const applicationInput = applicationContainer.querySelector('[data-multi-select-input]');
        const applicationList = applicationContainer.querySelector('[data-multi-select-list]');
        const applicationChips = applicationContainer.querySelector('[data-multi-select-chips]');
        const applicationHidden = applicationContainer.querySelector('[data-multi-select-hidden]');
        let applicationOptions = [];
        let selectedApplications = [];

        function renderApplicationList(filter = '') {
            applicationList.innerHTML = '';
            const query = filter.trim().toLowerCase();
            const available = applicationOptions.filter((option) => !selectedApplications.includes(String(option.application_id)) && (query === '' || option.application_name.toLowerCase().includes(query)));
            if (!available.length) { const empty = document.createElement('div'); empty.className = 'px-3 py-2 text-sm text-slate-500'; empty.textContent = applicationOptions.length ? 'No results found.' : 'No applications mapped to this project'; applicationList.appendChild(empty); return; }
            available.forEach((option) => { const button = document.createElement('button'); button.type = 'button'; button.dataset.value = option.application_id; button.className = 'w-full px-3 py-2 text-left text-sm text-slate-700 hover:bg-slate-50'; button.textContent = option.application_name; applicationList.appendChild(button); });
        }

        function renderApplicationChips() {
            applicationChips.innerHTML = ''; applicationHidden.innerHTML = '';
            selectedApplications.forEach((value) => { const option = applicationOptions.find((item) => String(item.application_id) === String(value)); if (!option) return; const chip = document.createElement('span'); chip.className = 'inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-700'; chip.textContent = option.application_name; const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'rounded-full bg-slate-200 px-1 text-slate-500 hover:bg-slate-300'; remove.textContent = '×'; remove.onclick = () => { selectedApplications = selectedApplications.filter((id) => id !== String(value)); renderApplicationChips(); renderApplicationList(applicationInput.value); }; chip.appendChild(remove); applicationChips.appendChild(chip); const hidden = document.createElement('input'); hidden.type = 'hidden'; hidden.name = 'application_ids[]'; hidden.value = value; applicationHidden.appendChild(hidden); });
        }

        applicationInput.addEventListener('focus', () => { renderApplicationList(applicationInput.value); applicationList.classList.remove('hidden'); });
        applicationInput.addEventListener('input', () => { renderApplicationList(applicationInput.value); applicationList.classList.remove('hidden'); });
        applicationList.addEventListener('click', (event) => { const button = event.target.closest('button[data-value]'); if (!button) return; selectedApplications.push(String(button.dataset.value)); renderApplicationChips(); renderApplicationList(applicationInput.value); });
        document.addEventListener('click', (event) => { if (!applicationContainer.contains(event.target)) applicationList.classList.add('hidden'); });
        document.getElementById('mapping-project').addEventListener('change', async function () { selectedApplications = []; applicationOptions = []; renderApplicationChips(); renderApplicationList(); if (!this.value) return; const response = await fetch(applicationOptionsUrl + '/' + this.value); const data = await response.json(); applicationOptions = data.applications || []; renderApplicationList(); });
        function openMappingModal() { document.getElementById('mapping-modal').classList.remove('hidden'); }
        function closeMappingModal() { document.getElementById('mapping-modal').classList.add('hidden'); }
        function exportMappingTable(format) { window.location.href = '{{ route('group.project.application.mapping') }}?format=' + encodeURIComponent(format); }
        document.getElementById('mapping-search').addEventListener('input', function () { const query = this.value.trim().toLowerCase(); let visibleCount = 0; document.querySelectorAll('tbody tr').forEach((row) => { if (row.classList.contains('empty-row')) return; const match = query === '' || row.textContent.toLowerCase().includes(query); row.classList.toggle('hidden', !match); if (match) visibleCount += 1; }); const emptyRow = document.querySelector('tbody tr.empty-row'); if (emptyRow) emptyRow.classList.toggle('hidden', visibleCount !== 0); });
    </script>
</x-app-layout>